### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adamlachmann** [drozhzhin-n-e/vue-pinch-zoom#2]
Hey,

Great library, any plans to add a license?

**Comment by drozhzhin-n-e** [comment]
Hi, I added a license - https://github.com/drozhzhin-n-e/vue-pinch-zoom/commit/650d02f458f8a521892b58d16d560d9400bfc792

**Comment by adamlachmann** [comment]
Thanks a lot! Once again - great job on the library!

**Comment by drozhzhin-n-e** [comment]
@adamlachmann thank!
